### PR TITLE
Memcache support, initially for tweets

### PR DESCRIPTION
**Pull request by johndrinkwater**
This could be expanded to support: servers.php and stream.php.

Work is part of #208 to reduce our initial load time to visit the site, as the server stalls for a moment querying this API.

Requires server to have memcached installed, configured, and have our local creds.php updated to include: `getMCHost()` + `getMCPort()`

### CODE REVIEW

**Comment by johndrinkwater** [comment]
The expiration times I picked are 10 minutes for server data, 20 minutes for tweets.
If anyone has better ideas for those, suggestions would be great.

Thinking at least for the server page, we should make the viewer aware content is stale with an ‘updated * ago’

**Comment by Corben78** [comment]
This PR works. memcached and php5-memcache (not php5-memcache**d** *doh*) are installed and active on the server.
Tested this PR on staging with:
```bash
git fetch origin refs/pull/211/head:pr211
git checkout pr211
```
And deleted it afterwards again:
```bash
git checkout master
git branch -D pr211
```
Ready to merge.

**Comment by johndrinkwater** [comment]
Lemme just check a few things, however watching Eurovision so it may take some minutes.

**Comment by johndrinkwater** [comment]
A not very scientific comparison to say having this enabled is useful.

/news
```
Before http://www.webpagetest.org/result/170513_1R_Q88/
1336 ms First Byte Time
2.138s Document Complete
```
```
After (cached) http://www.webpagetest.org/result/170513_10_YDN/
826 ms First Byte Time
1.710s Document Complete
```

/servers
```
Before http://www.webpagetest.org/result/170513_CH_Y8E/
599 ms First Byte Time
4.443s Document Complete
```

```
After (cached) http://www.webpagetest.org/result/170513_6B_YBA/
635 ms First Byte Time
1.659s Document Complete
```

**Comment by johndrinkwater** [comment]
Going to merge this in this state, stream work is not done but due to #212 we probably need to do some rethinking of that page before we do further work on it…

**Pull request merged**
