### PR TITLE
Remove our minified stylesheet to move it into a post-receive githook

### PR DESCRIPTION
**Pull request by johndrinkwater**
Also included some githooks that you can install locally (either copy
into ./git/hooks/ or symlink) that will fake a minified stylesheet after
the commit has been written.

This is intended to complete the work for
https://github.com/SteamLUG/steamlug.org/issues/192

Been discussing with @Corben78 about how we can best manage contributors that approach this and get stumped on the minification process. We have had previous PRs that demonstrate we don’t make it clear what happens, so this opts for a `post-commit` hook the user has to enable locally to make testing work for them.
That is an awkward step and I would love suggestions on how we improve this. Documentation would certainly help, but we still need some user configuration of hooks or repo variables to make development easier.

### CODE REVIEW

**Comment by johndrinkwater** [comment]
We would need to double up stylesheet headers, as the font sheet is merged into `bootstrap.steamlug.min.css` in the process. Does this seem ok?

```diff
diff --git a/includes/header.php b/includes/header.php
index 59873ff03476..c9b9db560872 100644
--- a/includes/header.php
+++ b/includes/header.php
@@ -61,7 +61,20 @@ header( 'Cache-Control: public, max-age=60' );
         <meta name="description" content="<?= $description; ?>" />
         <meta name="keywords" content="<?= $keywords; ?>" />
         <?= $rssLinks . "\n"; ?>
+<?php
+if ( file_exists( __DIR__ . '/../css/bootstrap.steamlug.min.css' ) ) {
+    echo <<<STYLE
         <link rel="stylesheet" href="/css/bootstrap.steamlug.min.css" type="text/css" />
+
+STYLE;
+} else {
+    echo <<<STYLE
+        <link rel="stylesheet" href="/css/bootstrap.steamlug.css" type="text/css" />
+        <link rel="stylesheet" href="/css/steamlugfont.css" type="text/css" />
+
+STYLE;
+}
+?>
         <link rel="icon" href="/mobile-favicon.png" sizes="192x192" />
         <script type="text/javascript">
             var serverTime = <?= microtime(true); ?>;
```

**Comment by Corben78** [comment]
Yeah, that serves the purpose.

**Comment by johndrinkwater** [comment]
Reworked to move the code away from the code dump.
```diff
diff --git a/includes/header.php b/includes/header.php
index 59873ff03476..7a6c4bed2580 100644
--- a/includes/header.php
+++ b/includes/header.php
@@ -16,6 +16,13 @@ if ( ! isset($pageTitle) ) {
 if ( ! isset($rssLinks) ) {
     $rssLinks = '<link rel="alternate" type="application/rss+xml" title="RSS" href="https://steamcommunity.com/groups/steamlug/rss/" />';
 }
+$styleLinks = '<link rel="stylesheet" href="/css/bootstrap.steamlug.min.css" type="text/css" />';
+if ( ! file_exists( __DIR__ . '/../css/bootstrap.steamlug.min.css' ) ) {
+    $styleLinks = <<<STYLE
+<link rel="stylesheet" href="/css/bootstrap.steamlug.css" type="text/css" />
+        <link rel="stylesheet" href="/css/steamlugfont.css" type="text/css" />
+STYLE;
+}
 $weareadmin = false;
 $logIn = "";
 if ( ! isset($skipAuth) ) {
@@ -61,7 +68,7 @@ header( 'Cache-Control: public, max-age=60' );
         <meta name="description" content="<?= $description; ?>" />
         <meta name="keywords" content="<?= $keywords; ?>" />
         <?= $rssLinks . "\n"; ?>
-        <link rel="stylesheet" href="/css/bootstrap.steamlug.min.css" type="text/css" />
+        <?= $styleLinks . "\n"; ?>
         <link rel="icon" href="/mobile-favicon.png" sizes="192x192" />
         <script type="text/javascript">
             var serverTime = <?= microtime(true); ?>;
```

**Comment by Corben78** [comment]
Next thing to add would be, to make sure the newest css file is loaded.
E.g. if the normal css files are updated, and the minified css isn't recreated, it would still load the old minified css file.

**Comment by johndrinkwater** [comment]
Is that urgent, does it block merging this? Does that mean we need to let our php site call the minification process, or keep hashed copies of the min.css file around?

* If the post-recieve hook fails to produce a minified file, the server will now send two sheets.
* If a user happens to have `bootstrap.steamlug.min.css` without noticing, it will cause them headaches but hopefully it shouldn’t take them more than a lunchbreak to discover it? 😉

**Comment by Corben78** [comment]
Can be merged.
My comment was just a reminder, so that issue is also addressed at some point.

**Pull request merged**
