### PR TITLE
BootStrap

### PR DESCRIPTION
**Pull request by swordfischer**
We can then focus on minor changes with the site.

### CODE REVIEW

**Comment by Cheeseness** [comment]
Was it OK to merge this when I said in #96 that I would be doing a review today? In future, if somebody's said they're going to look at stuff by a particular date, can we please at least give them that long to do so.

**Comment by Cheeseness** [comment]
Leaving a brain dump here since it makes sense to keep it in one place instead of making a separate issue for everything.

General feedback
* We've lost so much in the way of semantic classnames and helper IDs (for specific elements such as pollOptionLabel and for containers such as pollBox) - these mean we can no longer specifically style, address or script elements that might need contextually specific stuff
* We're using classnames for stuff which doesn't make semantic sense

Header/footer
* Menu disappears entirely on small window sizes - should it become a dropdown under the SteamLUG link?
* Headings are obscured when menus wrap
* Bullets back for the lists?
* Footer no longer uses footer tag?
* Beta notification shouldn't be removed, if it's time to turn beta off, set the variable to false. If it needs to look different, make it look different.
* Inline style tag on the body element?
* Nav div nesting is a little excessive (they're not even being used for styling are they?)

about.php
* About page doesn't need a footer element, has two closing small tags on line #19 

cast.php
* Time stuff is using button classes? WTF?
* Buttons can not have A elements in them
* Can't have divs inside p tags (countdown div)
* type attribute on audio element?
* Sorting headers need interaction cursor?

events.php
* Sorting headers need interaction cursor?
* Can't have divs inside p tags (countdown div)
* Do we really want comments as a column?

poll-functions.php
* Checkboxes for polls don't seem to work properly (and look like text boxes)? http://imgur.com/a/csNwp
* showPollSelector() needs elementID put back in. This was included so that we can look up specific stuff via Javascript if needed (for populating select elements dynamically, etc.)
* line 188, if we can't vote, we're now missing a block level element (which the form tag provides when you can vote)?

mumble.php
* Adds too many (2 extra?) closing divs (line #114 and #113?)

servers.php
* tfoot colspan is incorrect (should be 8
* Is tfoot necessary?

**Comment by johndrinkwater** [comment]
> Was it OK to merge this
Yes, it is so we can work on it today and for the rest of the week., our problem is always stalling on reviews; we have two branches, can we at least use them?

**Comment by johndrinkwater** [comment]
Proposal: remove the idea that we need a beta tag on the site.

**Comment by johndrinkwater** [comment]
@Cheeseness ‘cast.php type attribute on audio element?’

Am I misreading your comment here? This is on the audio element already.

**Comment by Cheeseness** [comment]
> Am I misreading your comment here? This is on the audio element already.

Ah, I meant to take that out of the list. It was a note to myself that it doesn't validate.

> Yes, it is so we can work on it today and for the rest of the week., our problem is always stalling on reviews; we have two branches, can we at least use them?

I don't think we ever want to leave the staging branch in a position where it's not ready to merge to live at short notice. I see it as being useful for checking integration and asking for broader feedback as needed before rolling things out, but any stuff that needs work should be resolved before a pull request is merged IMO.

> Right, have resolved some of the above issues

Cheers. That reduces my todo list by a bunch <3

I don't really like having my comments edited though. Can we avoid that in future please?

**Comment by Cheeseness** [comment]
I went through and restored the article elements. That's currently sitting in the semantic-fixes branch ( #118 ). if somebody can check it and make sure I haven't missed anything/broken validation, I'm happy to have it merged unless we want to deal with other semantic issues in there. On that note, do we also want to bring back the section element?

Another thing I did this evening was change the Cast "Click for details" button's classes to match the event page's corresponding button ( ec78fbb ). @swordfischer had a go at me in IRC for pushing changes without discussing them (this is the only commit that I've made tonight that wasn't for stuff that's been discussed). It seemed like a small thing - I'm happy to have it reverted if it's an undesirable change, but I think we should aim for consistency.

**Comment by johndrinkwater** [comment]
Been slowly poking at the style, the backend, and then at bootstrap to understand how it works. Thanks to @swordfischer we nearly have a fully mobile→desktop resizable site. 

There are still outstanding issues with the join our steam group button causing resize issues, but otherwise happy with current appearance. Some whitespace tightening would not go amiss. Going to open a bug to do another style sweep through, then time to consider moving to live?
screenshot 2015-01-23 114512

**Comment by Cheeseness** [comment]
The polling pages are still broken (functionality problems like this should've been resolved before the branch was merged). I have no idea how to fix them, and my motivation to work with Bootstrap is low. Somebody else is going to have to sort that one out.

**Comment by Cheeseness** [comment]
Also, have we sorted the problem with the navigation menu not being usable at low resolutions?

**Comment by johndrinkwater** [comment]
Resolved a few issues with polls https://github.com/SteamLUG/steamlug.org/compare/b0194a8...HEAD
Why is there so much whitespace inside the values for the polls?
eg: "
						http://steamcommunity.com/groups/steamlug#announcements/detail/127557410250969153					"

**Comment by Cheeseness** [comment]
Good question. I haven't spotted that, so I can't say without looking. Once I get on top of convention stuff, I can delve into it.

Is it in the poll description? It looks OK for me:
poll_source_screen

**Comment by johndrinkwater** [comment]
In poll-admin, poll details fields all have a lot of whitespace. 
screenshot 2015-01-23 134023

```
<input class="form-control" id="poll_title" name="poll_title" type="text" placeholder="The title of the poll" value='
						Which genres would you like to see more of?					'/>
```

**Comment by johndrinkwater** [comment]
Ooooh. I see why in the code. *fixes*

**Comment by Cheeseness** [comment]
I don't recall it doing that previously. Good catch.

**Comment by Cheeseness** [comment]
Need to test that voting actually works (it didn't last time I checked).

**Comment by johndrinkwater** [comment]
Right, https://github.com/SteamLUG/steamlug.org/compare/b0194a8...83e4044 resolves the whitespace issue. Can you make a new poll we can test on?

**Pull request merged**
