### PR TITLE
Revert new Steam sign-in button (#199)

### PR DESCRIPTION
**Pull request by her001**
This reverts commits
1b6341efe20d47f35ef838178ef32f433500b5c9,
4ba5cbfef0626cfd37376e65d4713fa541411747, and
8ce01235b48bbb8d37221e36487cbe589c148ab2.

These are the two commits from the pull request and the one related CSS
tweak that was made afterward.

### CODE REVIEW

**Comment by her001** [comment]
I don't like this. We are reverting something that was sitting for a long time without comment, with many requests for review, then merged before it was disputed.

But if people care enough, then this can be accepted.

**Comment by her001** [comment]
This has gone a day without comment. If anyone wants it badly enough, they can reopen it.

**Comment by Corben78** [comment]
Give people some time!

**Comment by johndrinkwater** [comment]
I may have time on Saturday, apologies if that is not soon enough.

**Comment by her001** [comment]
While I closed this a day after I opened it, and normally I wouldn't consider that to be enough time, the PR we would be reverting sat for over 9 months. I also kept asking for people to review our open PRs. You had time to respond.

And, as I said, you can reopen it. Which you have.

**Pull request closed without merging**
