### PR TITLE
Sign In Through Steam button/logged in avatar as right ending of navbar

### PR DESCRIPTION
**Pull request by Corben78**
Suggestion to move the login button/avatar to the right ending of navbar again, which imho is optically more appealing.
Tested on Desktop (Firefox/Chrome), Nexus 7 (Chrome, non-collapsed in landscape mode, collapsed in portrait mode), iPhone 6 (Safari, collapsed navbar).

### CODE REVIEW

**Comment by meklu** [comment]
I'd agree that it looks more pleasant. The `<li>` you added to get things to align looks a bit hacky though.

Although now that I took a look at our CSS it seems to fit right in anyway! :D

**Comment by johndrinkwater** [comment]
I dislike moving this button to the right, as it then sits all on its own, but that’s just like, my opinion man. If others want it, then it seems like this change should happen.

Inline styles are pretty :< though, can that be bumped into our stylesheet please - we don’t seem to use `navbar-right` anywhere else, so that is free to put it on. and yeah, Bootstrap does have a rather extensive CSS and .. we should probably go back over it, tidy it up and reduce it further.

**Comment by Corben78** [comment]
Regarding certain other sites, they all have a login or search field on the right. It closes the navbar and fits to to the overall width of the elements of the rest of the site.

Will change the CSS to make it less "hacky" :)

**Comment by johndrinkwater** [comment]
Would you be able to merge these changes into one commit? If not, it’s ok, can merge :)

**Pull request merged**
